### ISSUE TITLE
vocab_vectorizer(p.173)

### ISSUE THREAD

**Issue by cmucmm** [kwartler/text_mining#3]
In page 173, 

_> vectorizer <- vocab_vectorizer(vocab, + grow_dtm = FALSE, + skip_grams_window = 5)_

I got the following error message:

_Error in vocab_vectorizer(vocab, grow_dtm = FALSE, 
skip_grams_window = 5) : 
unused arguments (grow_dtm = FALSE, skip_grams_window = 5)_ 

Thanks in advance, 

Chang-Kyo Suh(ck@knu.ac.kr)

**Comment by kwartler** [comment]
Chang-Kyo Suh - I will investigate and get back to you.  I suspect the package has changed so I will recode if needed and post in the coming day or so.

**Comment by kwartler** [comment]
Check out Issue #4 for the rewrite of the function.  The package changed so parameters moved around.  In this case the following works:
```
iter <- itoken(tokens)
vectorizer <- vocab_vectorizer(vocab) #
tcm <- create_tcm(iter, vectorizer,grow_dtm = F, skip_grams_window = 5)
```

The error message is the clue
```
unused arguments (grow_dtm = FALSE, skip_grams_window = 5)
```
and the package docs led me the rest of the way!
