### ISSUE TITLE
R-Code

### ISSUE THREAD

**Issue by Matthias2018** [kwartler/text_mining#7]
I bought the printed version of this interesting book. Obviously the author is offering the data but not the R-Code for the different chapters online. Despite of some efforts I couldn't find the code-source. Yes, one can copy the code out of the book, but why this imposition?

**Comment by kwartler** [comment]
No one has ever really asked and were happy to read and do it themselves.  My pedagogical style is one of case study examples and having people follow along and learn by doing themselves (classic adult learning model).  That said, I certainly don't want to cause any issues to your learning.  Drop me a message on linkedin.com/in/edwardkwartler/ and I will get you the scripts.  Its also a great way to ask me questions that aren't really technical issues on github.  

And thanks for buying the book.  I hope you enjoy it and if compelled leave a positive review.
