### ISSUE TITLE
Full Code not appearing in section 6.2.3, pg 196 | Corrected

### ISSUE THREAD

**Issue by shawnbrar0804** [kwartler/text_mining#9]
In section 6.2.3, page 196 the last line of the code is not readable as shown in the following image(yellow highlighted `section):-`

![code](https://user-images.githubusercontent.com/40483330/41759665-34ad4700-760d-11e8-9866-ef9d459543ea.PNG)

For those of who are suffering from this the full code is as follows

```
clean.test <- headline.clean(test.headlines$headline)
test.dtm <- match.matrix(clean.test, weighting = tm::weightTfIdf, original.matrix = train.dtm)
```

**Comment by kwartler** [comment]
Thats weird...thank you for updating the github repo.  I appreciate it.
